# Generated by Django 3.0.8 on 2020-08-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Sci-fic', 'Sci-fic')], default='Action', max_length=40),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
