# Generated by Django 3.1 on 2020-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
