# Generated by Django 3.1 on 2020-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_auto_20200825_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('romance', 'Romance')], default='action', max_length=40),
        ),
    ]
